export const PET_ONE_INITIAL_STATE = {
  petOneName: {
    value: "",
    error: null,
    type: "text",
    label: "Pet Name",
    required: true,
  },
  petOneType: {
    value: "Dog",
    error: null,
    type: "select",
    options: ["Dog", "Cat"],
    label: "Type",
    required: true,
  },
  petOneBreed: {
    value: "",
    error: null,
    type: "text",
    label: "Breed",
    required: true,
  },
  petOneGender: {
    value: "Male",
    error: null,
    type: "select",
    options: ["Male", "Female"],
    label: "Gender",
    required: true,
  },
  petOneFixed: {
    value: "No",
    error: null,
    type: "select",
    options: ["No", "Yes"],
    label: "Fixed",
    required: true,
  },
  petOneColor: {
    value: "",
    error: null,
    type: "text",
    label: "Color",
    required: true,
  },
  petOneImage: {
    value: "",
    error: null,
    type: "text",
    label: "Image",
  },
  petOneLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Large Image",
  },
  petOneVaccinations: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations",
    required: true,
  },
  petOneVaccinationsLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations Large Image",
  },
  petOneAge: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Age",
    required: true,
  },
  petOneWeight: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Weight (lbs)",
    required: true,
  },
  petOneVet: {
    value: "",
    error: null,
    type: "text",
    label: "Vet",
    required: true,
  },
  petOnePreferredRunSize: {
    value: "Small",
    error: null,
    type: "select",
    options: ["Small", "Large", "Extra Large"],
    label: "Preferred Run Size",
    required: true,
  },
  petOneFeeding: {
    value: "",
    error: null,
    type: "text",
    label: "Feeding",
    required: true,
  },
  petOneFeedingCount: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Feeding Count",
    required: true,
  },
};

export const PET_TWO_INITIAL_STATE = {
  petTwoName: {
    value: "",
    error: null,
    type: "text",
    label: "Pet Name",
    required: true,
  },
  petTwoType: {
    value: "Dog",
    error: null,
    type: "select",
    options: ["Dog", "Cat"],
    label: "Type",
    required: true,
  },
  petTwoBreed: {
    value: "",
    error: null,
    type: "text",
    label: "Breed",
    required: true,
  },
  petTwoGender: {
    value: "Male",
    error: null,
    type: "select",
    options: ["Male", "Female"],
    label: "Gender",
    required: true,
  },
  petTwoFixed: {
    value: "No",
    error: null,
    type: "select",
    options: ["No", "Yes"],
    label: "Fixed",
    required: true,
  },
  petTwoColor: {
    value: "",
    error: null,
    type: "text",
    label: "Color",
    required: true,
  },
  petTwoImage: {
    value: "",
    error: null,
    type: "text",
    label: "Image",
  },
  petTwoLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Large Image",
  },
  petTwoVaccinations: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations",
    required: true,
  },
  petTwoVaccinationsLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations Large Image",
  },
  petTwoAge: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Age",
    required: true,
  },
  petTwoWeight: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Weight (lbs)",
    required: true,
  },
  petTwoVet: {
    value: "",
    error: null,
    type: "text",
    label: "Vet",
    required: true,
  },
  petTwoPreferredRunSize: {
    value: "Small",
    error: null,
    type: "select",
    options: ["Small", "Large", "Extra Large"],
    label: "Preferred Run Size",
    required: true,
  },
  petTwoFeeding: {
    value: "",
    error: null,
    type: "text",
    label: "Feeding",
    required: true,
  },
  petTwoFeedingCount: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Feeding Count",
    required: true,
  },
};

export const PET_THREE_INITIAL_STATE = {
  petThreeName: {
    value: "",
    error: null,
    type: "text",
    label: "Pet Name",
    required: true,
  },
  petThreeType: {
    value: "Dog",
    error: null,
    type: "select",
    options: ["Dog", "Cat"],
    label: "Type",
    required: true,
  },
  petThreeBreed: {
    value: "",
    error: null,
    type: "text",
    label: "Breed",
    required: true,
  },
  petThreeGender: {
    value: "Male",
    error: null,
    type: "select",
    options: ["Male", "Female"],
    label: "Gender",
    required: true,
  },
  petThreeFixed: {
    value: "No",
    error: null,
    type: "select",
    options: ["No", "Yes"],
    label: "Fixed",
    required: true,
  },
  petThreeColor: {
    value: "",
    error: null,
    type: "text",
    label: "Color",
    required: true,
  },
  petThreeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Image",
  },
  petThreeLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Large Image",
  },
  petThreeVaccinations: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations",
    required: true,
  },
  petThreeVaccinationsLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations Large Image",
  },
  petThreeAge: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Age",
    required: true,
  },
  petThreeWeight: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Weight (lbs)",
    required: true,
  },
  petThreeVet: {
    value: "",
    error: null,
    type: "text",
    label: "Vet",
    required: true,
  },
  petThreePreferredRunSize: {
    value: "Small",
    error: null,
    type: "select",
    options: ["Small", "Large", "Extra Large"],
    label: "Preferred Run Size",
    required: true,
  },
  petThreeFeeding: {
    value: "",
    error: null,
    type: "text",
    label: "Feeding",
    required: true,
  },
  petThreeFeedingCount: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Feeding Count",
    required: true,
  },
};

export const PET_FOUR_INITIAL_STATE = {
  petFourName: {
    value: "",
    error: null,
    type: "text",
    label: "Pet Name",
    required: true,
  },
  petFourType: {
    value: "Dog",
    error: null,
    type: "select",
    options: ["Dog", "Cat"],
    label: "Type",
    required: true,
  },
  petFourBreed: {
    value: "",
    error: null,
    type: "text",
    label: "Breed",
    required: true,
  },
  petFourGender: {
    value: "Male",
    error: null,
    type: "select",
    options: ["Male", "Female"],
    label: "Gender",
    required: true,
  },
  petFourFixed: {
    value: "No",
    error: null,
    type: "select",
    options: ["No", "Yes"],
    label: "Fixed",
    required: true,
  },
  petFourColor: {
    value: "",
    error: null,
    type: "text",
    label: "Color",
    required: true,
  },
  petFourImage: {
    value: "",
    error: null,
    type: "text",
    label: "Image",
  },
  petFourLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Large Image",
  },
  petFourVaccinations: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations",
    required: true,
  },
  petFourVaccinationsLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations Large Image",
  },
  petFourAge: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Age",
    required: true,
  },
  petFourWeight: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Weight (lbs)",
    required: true,
  },
  petFourVet: {
    value: "",
    error: null,
    type: "text",
    label: "Vet",
    required: true,
  },
  petFourPreferredRunSize: {
    value: "Small",
    error: null,
    type: "select",
    options: ["Small", "Large", "Extra Large"],
    label: "Preferred Run Size",
    required: true,
  },
  petFourFeeding: {
    value: "",
    error: null,
    type: "text",
    label: "Feeding",
    required: true,
  },
  petFourFeedingCount: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Feeding Count",
    required: true,
  },
};

export const PET_FIVE_INITIAL_STATE = {
  petFiveName: {
    value: "",
    error: null,
    type: "text",
    label: "Pet Name",
    required: true,
  },
  petFiveType: {
    value: "Dog",
    error: null,
    type: "select",
    options: ["Dog", "Cat"],
    label: "Type",
    required: true,
  },
  petFiveBreed: {
    value: "",
    error: null,
    type: "text",
    label: "Breed",
    required: true,
  },
  petFiveGender: {
    value: "Male",
    error: null,
    type: "select",
    options: ["Male", "Female"],
    label: "Gender",
    required: true,
  },
  petFiveFixed: {
    value: "No",
    error: null,
    type: "select",
    options: ["No", "Yes"],
    label: "Fixed",
    required: true,
  },
  petFiveColor: {
    value: "",
    error: null,
    type: "text",
    label: "Color",
    required: true,
  },
  petFiveImage: {
    value: "",
    error: null,
    type: "text",
    label: "Image",
  },
  petFiveLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Large Image",
  },
  petFiveVaccinations: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations",
    required: true,
  },
  petFiveVaccinationsLargeImage: {
    value: "",
    error: null,
    type: "text",
    label: "Vaccinations Large Image",
  },
  petFiveAge: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Age",
    required: true,
  },
  petFiveWeight: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Weight (lbs)",
    required: true,
  },
  petFiveVet: {
    value: "",
    error: null,
    type: "text",
    label: "Vet",
    required: true,
  },
  petFivePreferredRunSize: {
    value: "Small",
    error: null,
    type: "select",
    options: ["Small", "Large", "Extra Large"],
    label: "Preferred Run Size",
    required: true,
  },
  petFiveFeeding: {
    value: "",
    error: null,
    type: "text",
    label: "Feeding",
    required: true,
  },
  petFiveFeedingCount: {
    value: "1",
    error: null,
    type: "number",
    inputMode: "numeric",
    min: "1",
    label: "Feeding Count",
    required: true,
  },
};

export const INITIAL_PETS_STATE = {
  ...PET_ONE_INITIAL_STATE,
  ...PET_TWO_INITIAL_STATE,
  ...PET_THREE_INITIAL_STATE,
  ...PET_FOUR_INITIAL_STATE,
  ...PET_FIVE_INITIAL_STATE,
};
