import { group } from "console";

export const petDetailsInputs = [
  {
    name: "name",
    label: "Pet Name",
    type: "text",
    group: "Pet Info",
    // required: true,
  },
  {
    name: "type",
    label: "Type",
    type: "select",
    group: "Pet Info",
    options: [
      { value: "dog", label: "Dog" },
      { value: "cat", label: "Cat" },
    ],
    // required: true,
  },

  {
    name: "breed",
    label: "Breed",
    type: "text",
    group: "Pet Info",
    // required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    group: "Pet Info",
    options: [
      { value: "female", label: "Female" },
      { value: "male", label: "Male" },
    ],
    // required: true,
  },
  {
    name: "fixed",
    label: "Fixed",
    type: "select",
    group: "Pet Info",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    // required: true,
  },
  {
    name: "color",
    label: "Color",
    type: "text",
    group: "Pet Info",
    // required: true,
  },
  {
    name: "image",
    label: "Image",
    type: "image",
    // required: true,
  },
  {
    name: "vaccinations",
    label: "Vaccinations",
    type: "image",
    group: "Vaccines",
    // required: true,
  },

  {
    name: "distemperVaccine",
    label: "Distemper Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "bordetellaVaccine",
    label: "Bordetella Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "rabiesVaccine",
    label: "Rabies Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "parvoVirusesVaccine",
    label: "Parvo Viruses Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "felinLeukemiaVaccine",
    label: "Felin Leukemia Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "felineFvrcpVaccine",
    label: "Feline Fvrcp Vaccine",
    type: "text",
    group: "Vaccines",
    // required: true,
  },
  {
    name: "age",
    label: "Age",
    type: "text",
    group: "Pet Info",
    // required: true,
  },
  {
    name: "weight",
    label: "Weight",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "vet",
    label: "Vet",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "preferredRunSize",
    label: "Preferred Run Size",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "feeding",
    label: "Feeding",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "feedingCount",
    label: "Feeding Count",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "feedingTimesPerDay",
    label: "Feeding Times Per Day",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "medications",
    label: "Medications",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "medicationInstructions",
    label: "Medication Instructions",
    type: "text",
    group: "Boarding",
    // required: true,
  },
  {
    name: "reservationId",
    label: "Reservation ID",
    type: "text",
    hidden: true,
    // required: true,
  },
];
