import { statesArray } from "../Reservations/formInitialState";

export const INITIAL_QUESTIONNAIRE_USER_DETAILS = {
  email: {
    value: "",
    error: null,
    type: "text",
    inputMode: "email",
    label: "Email",
    disabled: false,
  },
  name: {
    value: "",
    error: null,
    type: "text",
    label: "First Name",
    required: false,
  },
  lastName: {
    value: "",
    error: null,
    type: "text",
    label: "Last Name",
    required: false,
  },
  address: {
    value: "",
    error: null,
    type: "text",
    label: "Address",
    required: false,
  },
  unit: {
    value: "",
    error: null,
    type: "text",
    label: "Unit",
  },
  city: {
    value: "",
    error: null,
    type: "text",
    label: "City",
    required: false,
  },
  state: {
    value: "",
    error: null,
    type: "select",
    label: "State",
    required: false,
    options: statesArray,
  },
  zip: {
    value: "",
    error: null,
    type: "text",
    label: "Zip",
    required: false,
  },
  phone: {
    value: "",
    error: null,
    type: "text",
    inputMode: "numeric",
    minLength: 10,
    maxLength: 16,
    label: "Phone",
    required: false,
    hint: `Format: 123-456-7890`,
  },
};

export const INITIAL_QUESTIONNAIRE_PREVIOUS_TRAINING = {
  ownedDogBefore: {
    value: "",
    error: null,
    type: "radio",
    label: "Have you ever owned a dog before?",
    required: false,
    options: ["Yes", "No"],
  },
  trainedDogBefore: {
    value: "",
    error: null,
    type: "radio",
    label: "Have you ever trained a dog before?",
    required: false,
    options: ["Yes", "No"],
  },
  interestInTraining: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Are you interested in training your dog and willing to make a commitment to train your dog?",
    required: false,
    options: ["Yes", "No"],
  },
  trainingGoals: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "What do you want to get most out of training?",
    required: false,
  },
  previousTraining: {
    value: "",
    error: null,
    type: "radio",
    label: "Has your present dog had any previous training?",
    required: false,
    options: ["Yes", "No"],
  },
  previousTrainingLocation: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If yes, where did you train him/her?",
    required: false,
  },
  leashResponse: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How does your dog respond on a leash?",
    required: false,
  },
  leashBehaviors: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label:
      "Does he/she tug and pull? Does he/she chew on the leash? Does he/she trap the leash with his/her paws and attempt to take control?",
    required: false,
  },
  recallCommand: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog come when called?",
    required: false,
    options: ["Yes", "No"],
  },
  recallPercentage: {
    value: "",
    error: null,
    type: "text",
    inputMode: "numeric",
    label: "If yes, what % of the time?",
    required: false,
  },
  comeInsideOutside: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog come both inside the house and outside?",
    required: false,
    options: ["Yes", "No"],
  },
  correctedBehavior: {
    value: "",
    error: null,
    type: "radio",
    label: "Have you ever corrected your dog's behavior?",
    required: false,
    options: ["Yes", "No"],
  },
  correctedBehaviorDetails: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If yes, what behavior and how have you corrected?",
    required: false,
  },
  physicalPunishment: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Have you ever hit your dog with your hand or an object to correct his/her behavior?",
    required: false,
    options: ["Yes", "No"],
  },
  carRideBehavior: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label:
      "How does your dog respond when going for a car ride? Does he/she get nervous, bark, jump, or get ill?",
    required: false,
  },
  obedienceWords: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label:
      "Have you taught your dog any obedience words, such as sit, stay, heel, come, down, or stand? What words have you taught your dog?",
    required: false,
  },
  tricksTaught: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label:
      "Have you taught your dog any tricks, such as shake, rollover, and play dead, etc?",
    required: false,
  },
  demandingAttention: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Is your dog playful and generally demanding of attention? That is, does he/she nudge you for pets or shove toys at you for play?",
    required: false,
    options: ["Yes", "No"],
  },
  reasonForOwning: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "What is your reason for owning a dog?",
    required: false,
  },
  additionalInfo: {
    value: "",
    error: null,
    type: "textarea",
    label:
      "Please provide any additional important information that was not addressed in the above questionnaire.",
    required: false,
  },
};

export const INITIAL_QUESTIONNAIRE_PET_FAMILY_HISTORY = {
  adultsInHome: {
    value: "",
    error: null,
    type: "text",
    inputMode: "numeric",
    label: "How many adults live in your home?",
    required: false,
  },
  childrenInHome: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you have children in your home?",
    required: false,
    options: ["Yes", "No", "Occasionally"],
  },
  childrenAges: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If so, what are their ages?",
    required: false,
  },
  referredBy: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How were you referred to our services?",
    required: false,
  },
  petAgeWhenAcquired: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How old was your pet when you acquired him/her?",
    required: false,
  },
  petAgeNow: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How old is your pet now?",
    required: false,
  },
  whereDidYouGetYourDog: {
    value: "",
    error: null,
    type: "radio",
    label: "Where did you get your dog?",
    required: false,
    options: [
      "Professional breeder",
      "Back-yard breeder",
      "Pet store",
      "Rescue organization",
      "Friend or family member",
      "Ad in the paper",
      "Other (please explain on next line)",
    ],
  },
  whereDidYouGetYourDogOther: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "Please tell us where you got your dog.",
  },
  metAndInteractedWithParents: {
    value: "",
    error: null,
    type: "radio",
    label: "Did you meet and interact with your dog's mother and father?",
    required: false,
    options: ["Yes", "No"],
  },
  reasonForNotMeetingParents: {
    value: "",
    error: null,
    type: "text",
    label: "If no, why?",
  },
  wereParentsFriendly: {
    value: "",
    error: null,
    type: "text",
    label: "If yes, were they both friendly?",
  },
};

export const INITIAL_QUESTIONNAIRE_PET_HEALTH = {
  hipsCertified: {
    value: "",
    error: null,
    type: "radio",
    label: "Were the hips of the dam and sire OFA certified?",
    required: false,
    options: ["Yes", "No", "I don't know"],
  },
  dogHousebroken: {
    value: "",
    error: null,
    type: "radio",
    label: "Is your dog housebroken?",
    required: false,
    options: ["Yes", "No"],
  },
  dogPaperTrained: {
    value: "",
    error: null,
    type: "radio",
    label: "Is or was your dog paper-trained?",
    required: false,
    options: ["Yes", "No"],
  },
  dogExcitementPiddle: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog excitement piddle or submissive urinate?",
    required: false,
    options: ["Yes", "No"],
  },
  dogFoodAndStools: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    required: false,
    label:
      "What type of food do you feed your dog? Are his/her stools consistently firm and solid?",
  },
  dogCrateTrained: {
    value: "",
    error: null,
    type: "radio",
    label: "Is your dog crate trained?",
    required: false,
    options: ["Yes", "No"],
  },
  dogCrateType: {
    value: "",
    error: null,
    type: "radio",
    label: "What type of crate do you use?",
    options: ["Wire", "Plastic"],
  },
  crateLocation: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "Where is the crate located?",
    required: false,
  },
  cratePreference: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Does your dog like his/her crate, or does he/she stress and try to escape?",
    required: false,
    options: ["Likes Crate", "Stressed / tries to escape"],
  },
  crateUsage: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "When do you use the crate?",
    required: false,
  },
  eliminationInCrate: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog eliminate in the crate?",
    required: false,
    options: ["Yes", "No"],
  },
  eliminationRoutine: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How do you take your dog out to eliminate?",
    required: false,
  },
  dogExercise: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Is your dog leashed walked, supervised loose, or do you have a fenced yard?",
    required: false,
    options: ["Leashed Walked", "Supervised Loose", "Fenced Yard"],
  },
  healthProblems: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog have a history of health problems?",
    required: false,
    options: ["Yes", "No"],
  },
  healthProblemsExplanation: {
    value: "",
    error: null,
    type: "textarea",
    label: "If yes, explain.",
    required: false,
  },
};

export const INITIAL_QUESTIONNAIRE_PET_BEHAVIOR = {
  watchdogBehavior: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog engage in a watchdog barking behavior?",
    required: false,
    options: ["Yes", "No"],
  },
  objectDestruction: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog destroy objects?",
    required: false,
    options: ["Yes", "No"],
  },
  jumpingBehavior: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog jump on people?",
    required: false,
    options: ["Yes", "No"],
  },
  jumpingCommand: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label:
      "What do you say to your dog when he/she jumps on you or other people?",
    required: false,
  },
  jumpingResponse: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "What do you do when your dog jumps on people?",
    required: false,
  },
  jumpingDesire: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you want your dog to jump on you or other people?",
    required: false,
    options: ["Yes", "No"],
  },
  mouthBehavior: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Does your dog mouth (put his/her mouth on your hands or grab your clothing)?",
    required: false,
    options: ["Yes", "No"],
  },
  aggressiveBehavior: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Has your dog ever nipped, growled at, or bitten you or anyone else?",
    required: false,
    options: ["Yes", "No"],
  },
  aggressiveExplanation: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If yes, please explain.",
    required: false,
  },
  furnitureRules: {
    value: "",
    error: null,
    type: "radio",
    label: "Is your dog allowed on the furniture?",
    required: false,
    options: ["Yes", "No"],
  },
  furnitureUsage: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog get on the furniture?",
    required: false,
    options: ["Yes", "No"],
  },
  diggingHabits: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog dig holes in the yard?",
    required: false,
    options: ["Yes", "No"],
  },
  doorDashBehavior: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog door dash (escape or try to escape out of the door)?",
    required: false,
    options: ["Yes", "No"],
  },
  objectStealing: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Does your dog steal objects for attention (pick up objects that don't belong to her and run away when you try to get them)?",
    required: false,
    options: ["Yes", "No"],
  },
  stolenObjectTypes: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If yes, what kind of objects?",
    required: false,
  },
};

export const INITIAL_QUESTIONNAIRE_PET_BEHAVIOR_TO_OTHER_ANIMALS = {
  hasCat: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you have a cat?",
    required: false,
    options: ["Yes", "No"],
  },
  catLitterBoxAccess: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog get into the cat's litter box?",
    required: false,
    options: ["Yes", "No"],
  },
  catAggression: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog aggress toward the cat?",
    required: false,
    options: ["Yes", "No"],
  },
  otherDogPresence: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you have another dog in your environment?",
    required: false,
    options: ["Yes", "No"],
  },
  dogRelationships: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How do your dogs get along?",
    required: false,
  },
  objectRemoval: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Can you take objects away from your dog without signs of aggression (e.g., food, toys, etc.)?",
    required: false,
    options: ["Yes", "No"],
  },
  tugOfWar: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you or anyone else play tug-of-war with your dog?",
    required: false,
    options: ["Yes", "No"],
  },
  tugWith: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "If yes, what do you tug with?",
    required: false,
  },
  wrestling: {
    value: "",
    error: null,
    type: "radio",
    label: "Do you or anyone wrestle or rough house with your dog?",
    required: false,
    options: ["Yes", "No"],
  },
  chaseGames: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Do you play chase games with your dog (do you chase your dog around the house or yard)?",
    required: false,
    options: ["Yes", "No"],
  },
  playStyle: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "How do you play with your dog?",
    required: false,
  },
  sleepLocation: {
    value: "",
    error: null,
    type: "text",
    inputMode: "text",
    label: "Where does your dog sleep at night?",
    required: false,
  },
  restingPlaceGrowling: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Has your dog ever growled at you when disturbed in his/her favorite resting place?",
    required: false,
    options: ["Yes", "No"],
  },
  blockingBehavior: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog attempt to block you from leaving your environment?",
    required: false,
    options: ["Yes", "No"],
  },
  fearOfNoises: {
    value: "",
    error: null,
    type: "radio",
    label: "Is your dog afraid of thunderstorms or loud noises?",
    required: false,
    options: ["Yes", "No"],
  },
  reactToStrangersEnter: {
    value: "",
    error: null,
    type: "radio",
    label:
      "How does your dog normally react to strangers that enter your environment?",
    required: false,
    options: ["Friendly", "Aggressive", "Shy"],
  },
  reactToStrangersOutOfHome: {
    value: "",
    error: null,
    type: "radio",
    label:
      "How does your dog normally react to strangers when you are out of your environment?",
    required: false,
    options: ["Friendly", "Aggressive", "Shy"],
  },
  reactToChildren: {
    value: "",
    error: null,
    type: "radio",
    label: "Does your dog react differently to children?",
    required: false,
    options: ["Yes", "No", "Never around children"],
  },
  parksAndWoodedAreas: {
    value: "",
    error: null,
    type: "radio",
    label:
      "Do you take your dog to parks or wooded areas and let him/her run free?",
    required: false,
    options: ["Yes", "No"],
  },
};

export const INITIAL_QUESTIONNAIRE_FORM_STATE = {
  ...INITIAL_QUESTIONNAIRE_USER_DETAILS,
  ...INITIAL_QUESTIONNAIRE_PET_FAMILY_HISTORY,
  ...INITIAL_QUESTIONNAIRE_PET_HEALTH,
  ...INITIAL_QUESTIONNAIRE_PET_BEHAVIOR,
  ...INITIAL_QUESTIONNAIRE_PET_BEHAVIOR_TO_OTHER_ANIMALS,
  ...INITIAL_QUESTIONNAIRE_PREVIOUS_TRAINING,
};

export const getQuestionnaireFormFields = ({ user }) => {
  if (user) {
    for (const key in user) {
      if (user.hasOwnProperty(key) && INITIAL_QUESTIONNAIRE_FORM_STATE[key]) {
        INITIAL_QUESTIONNAIRE_FORM_STATE[key].value = user[key];
        INITIAL_QUESTIONNAIRE_FORM_STATE[key].disabled = true;
      }
    }
  }
  return INITIAL_QUESTIONNAIRE_FORM_STATE;
};
